"""
Pydantic models for the Meeting Minutes application.
All data structures used across services and API endpoints.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class SpeakerSegment(BaseModel):
    """A time segment associated with a specific speaker."""

    speaker_label: str = Field(..., description="Speaker identifier (e.g., SPEAKER_00)")
    start_time: float = Field(..., description="Start time in seconds")
    end_time: float = Field(..., description="End time in seconds")

    @property
    def duration(self) -> float:
        """Duration of the segment in seconds."""
        return self.end_time - self.start_time


class TranscriptChunk(BaseModel):
    """A chunk of transcribed text with metadata."""

    chunk_id: str = Field(..., description="Unique identifier for this chunk")
    speaker_label: str = Field(..., description="Speaker who spoke this text")
    start_time: float = Field(..., description="Start time in seconds")
    end_time: float = Field(..., description="End time in seconds")
    text: str = Field(..., description="Transcribed text")
    language: str | None = Field(None, description="Detected language code (e.g., 'zh', 'en')")
    confidence: float | None = Field(None, description="Transcription confidence score")

    def to_context_string(self) -> str:
        """Format chunk for LLM context."""
        lang_str = f" [{self.language}]" if self.language else ""
        time_str = f"[{self.start_time:.1f}s - {self.end_time:.1f}s]"
        return f"{time_str} {self.speaker_label}{lang_str}: {self.text}"


class MeetingTranscript(BaseModel):
    """Complete transcript of a meeting with all chunks."""

    meeting_id: str = Field(..., description="Unique meeting identifier")
    chunks: list[TranscriptChunk] = Field(default_factory=list, description="Transcript chunks")
    speakers: list[str] = Field(default_factory=list, description="List of unique speakers")
    duration: float = Field(..., description="Total meeting duration in seconds")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    def get_full_text(self) -> str:
        """Get complete transcript as plain text."""
        return "\n".join(chunk.to_context_string() for chunk in self.chunks)

    def get_speaker_turns(self) -> dict[str, int]:
        """Count speaking turns per speaker."""
        turns: dict[str, int] = {}
        for chunk in self.chunks:
            turns[chunk.speaker_label] = turns.get(chunk.speaker_label, 0) + 1
        return turns


class SummaryResponse(BaseModel):
    """Meeting summary generated by LLM."""

    summary: str = Field(..., description="Overall meeting summary (1-2 paragraphs)")
    action_items: list[str] = Field(
        default_factory=list, description="List of action items identified"
    )
    key_decisions: list[str] = Field(
        default_factory=list, description="Key decisions made in the meeting"
    )
    topics: list[str] = Field(default_factory=list, description="Main topics discussed")


class MeetingResult(BaseModel):
    """Complete result of processing a meeting audio file."""

    meeting_id: str = Field(..., description="Unique meeting identifier")
    transcript: MeetingTranscript = Field(..., description="Full transcript")
    summary: SummaryResponse = Field(..., description="AI-generated summary")
    processed_at: datetime = Field(default_factory=datetime.utcnow)


class QARequest(BaseModel):
    """Request for question answering over a meeting transcript."""

    question: str = Field(..., description="Question to answer", min_length=1)
    top_k: int | None = Field(5, description="Number of context chunks to retrieve", ge=1, le=20)


class QAResponse(BaseModel):
    """Response to a question about the meeting."""

    question: str = Field(..., description="Original question")
    answer: str = Field(..., description="LLM-generated answer")
    context_chunks: list[TranscriptChunk] = Field(
        default_factory=list, description="Relevant transcript chunks used"
    )
    confidence: str | None = Field(None, description="Confidence level of the answer")


class UploadResponse(BaseModel):
    """Response after uploading and processing a meeting."""

    meeting_id: str
    message: str
    transcript_preview: str | None = None
    summary: SummaryResponse | None = None

